### ISSUE TITLE
My App crashes around 1 minute into the game

### ISSUE THREAD

**Issue by jeaabr** [poma/HotsStats#15] opened 2016-03-17 12:12 UTC
It works as it should during the loading screens but crashes afterwards 1 minute into the game.

It would also be nice to have a feature where you can select which monitor you want it to appear and stay on.

I hope it helps you by providing the log. :)

Here's the log:

[17.03.2016 12.42.33] Replay copy error: System.IO.IOException: The process cannot access the file 'D:\Libraries\Documents\Heroes of the Storm\Accounts\400763821\2-Hero-1-1187160\Saves\Rejoin\0x9B3A20B0.StormSave' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at StatsFetcher.FileProcessor.ProcessRejoin(String path, Game game)

[17.03.2016 12.42.34] Unhandled exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at StatsFetcher.FileProcessor.ProcessRejoin(String path, Game game)
   at StatsDisplay.SettingsWindow.ProcessRejoinFile(String path)
   at StatsDisplay.SettingsWindow.<>c__DisplayClass5_1.<.ctor>b__4()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

[17.03.2016 12.42.35] Critical exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at StatsFetcher.FileProcessor.ProcessRejoin(String path, Game game)
   at StatsDisplay.SettingsWindow.ProcessRejoinFile(String path)
   at StatsDisplay.SettingsWindow.<>c__DisplayClass5_1.<.ctor>b__4()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at StatsDisplay.App.Main()

**Comment by poma** [comment] 2016-03-17 13:22
Try this release https://github.com/poma/HotsStats/releases/tag/0.4.1-debug.1

**Comment by benjamin-small** [comment] 2016-03-17 13:45
This is a duplicate of issue #8

**Comment by poma** [comment] 2016-03-17 13:50
Continue discussion in issue #8

**Closed as completed** 2016-03-17 13:50 UTC
