### ISSUE TITLE
Crash at the 1:00 mark

### ISSUE THREAD

**Issue by Merlyn42** [poma/HotsStats#14] opened 2016-03-17 11:46 UTC
App crashes at the 1:00 mark
I do not have my documents folder in the standard place, perhaps this is causing an issue

[log.txt](https://github.com/poma/HotsStats/files/177760/log.txt)

Edit: tried with running as Administrator, didn't help.

Windows 10

**Comment by poma** [comment] 2016-03-17 13:22
Try this release https://github.com/poma/HotsStats/releases/tag/0.4.1-debug.1

**Comment by benjamin-small** [comment] 2016-03-17 13:44
This is a duplicate of issue #8

**Closed as completed** 2016-03-17 13:49 UTC

**Comment by poma** [comment] 2016-03-17 13:51
Continue discussion in issue #8
